project:
  type: website

execute: 
  freeze: auto
language: 
  search-text-placeholder: Search

website: 
  title: "Digital Scholarship & Data Science Topic Guides"
  favicon: logo/favicon.ico
  google-analytics: 
    tracking-id: "G-54HL7T1Z2K"
  repo-url: https://github.com/libereurope/ds-topic-guides/
  repo-subdir: book
  repo-actions: [source, issue] 
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Currently under construction** - we're hard at work finalising the content of _DS Topic Guides_ ahead of our July 4 launch at the LIBER Annual 2025 conference! Stay tuned!"
    type: light
    position: below-navbar
    
  navbar:
    background: primary
    pinned: true
    search: true
    type: overlay
    logo: logo/Liber-DS-logo-long-blue.png
    
    right:
      - text: "Topic Guides"
        href: topicguides.qmd
      - text: "About"
        href: project-overview.qmd 
      - text: "Contribute"
        menu:
        - contributing.qmd
        - guidelines.qmd
        - licensing.qmd
  sidebar:  
      - title: "Topic Guides"
        style: "docked"
        background: light
        contents:
          - topicguides.qmd
          - text: "---"
          - gettingstarted.qmd
          - text: "---"
          - ai-ml.qmd
          - text: "---"
          - api.qmd
          - text: "---"
          - atr.qmd
          - text: "---"
          - collectionsasdata.qmd
          - text: "---"
          - computer-vision.qmd
          - text: "---"
          - copyright.qmd
          - text: "---"
          - crowdsourcing.qmd
          - text: "---"
          - dataviz.qmd
          - text: "---"
          - digitalmapping.qmd
          - text: "---"
          - digitisation.qmd
          - text: "---"
          - github.qmd
          - text: "---"
          - iiif.qmd
          - text: "---"
          - lod.qmd
          - text: "---"
          - programming.qmd
          - text: "---"
          - openresearch.qmd
          - text: "---"
          - dstp.qmd
          - text: "---"
          - workingwdata.qmd 
  page-footer: 
    border: false
    background: "#EEB111"
    center: | 
      A 2023-2027 <a href="https://libereurope.eu/working-groups">LIBER Working Group</a> collaboration between <a href="https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/">Digital Scholarship and Digital Cultural Heritage </a> and <a href="https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/">Data Science in Libraries</a> 
    right:
      - icon: github
        href: https://github.com/libereurope/ds-topic-guides

format:
  html:
    theme: [flatly, custom.scss]
    toc: true
    toc-location: right
    toc-title: Jump to...
    toc-depth: 2

    template-path: partials
    template-partials:
      - title-block.html







#About DS Essentials - Topic Guides  -   Additional Resources  -  Contribute   -   Search

book:  
  title: "Digital Scholarship & Data Science Topic Guides for Library Professionals"
  google-analytics: 
    tracking-id: "G-54HL7T1Z2K"
  reader-mode: true
  search: true
  page-footer: 
    border: false
    background: dark
    left: | 
      A 2023-2027 <a href="https://libereurope.eu/working-groups">LIBER Working Group</a> collaboration between <a href="https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/">Digital Scholarship and Digital Cultural Heritage </a> and <a href="https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/">Data Science in Libraries</a> 
  
  chapters:
    - part: "**About**"
      chapters:
        - index.qmd
        - project-overview.qmd
        - contributing.qmd
        - guidelines.qmd
        - licensing.qmd
        - contact.qmd
    - topicguides.qmd
    - ai-ml.qmd
    - copyright.qmd
    - atr.qmd
    - collectionsasdata.qmd
    - computer-vision.qmd
    - lod.qmd
    - iiif.qmd
    - dataviz.qmd
    - digitalmapping.qmd
    - digitisation.qmd
    - crowdsourcing.qmd
    - github.qmd
    - workingwdata.qmd
    - part: "**General Resources**"
      chapters:
        - dstp.qmd
        - references.qmd
        - reports.qmd
        - training-platforms.qmd
        - networks.qmd
        
    
  sidebar:
    logo: images/NewLogo.png
    style: "docked"
    collapse-level: 1

  comments: 
    utterances:
      repo: libereurope/ds-topic-guides

bibliography: references.bib




